before_script:
  - ssh-keyscan -t rsa,dsa,ecdsa github.com $ADDITIONAL_GIT_SERVERS > /etc/ssh/ssh_known_hosts

variables:
  UPSTREAM_REPOSITORY: "git@github.com:spreedbox/nextcloud-debian.git"

mirror-branches:
  stage: deploy
  except:
    - tags
  script:
    - git remote add upstream $UPSTREAM_REPOSITORY || true
    - git fetch upstream
    - git push --progress upstream HEAD:$CI_BUILD_REF_NAME

mirror-tags:
  stage: deploy
  only:
    - tags
  script:
    - git remote add upstream $UPSTREAM_REPOSITORY || true
    - git fetch upstream
    - git push --progress --tags upstream
